// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_bootcamp_c6_clean_arch/test/features/data/repos/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:elevate_bootcamp_c6_clean_arch/features/data/api/home_api_client.dart'
    as _i10;
import 'package:elevate_bootcamp_c6_clean_arch/features/data/datasources/contract/home_local_datasource.dart'
    as _i8;
import 'package:elevate_bootcamp_c6_clean_arch/features/data/mapper/home_mapper.dart'
    as _i11;
import 'package:elevate_bootcamp_c6_clean_arch/features/data/models/banners_response.dart'
    as _i2;
import 'package:elevate_bootcamp_c6_clean_arch/features/data/models/categories_response.dart'
    as _i4;
import 'package:elevate_bootcamp_c6_clean_arch/features/data/models/products_response.dart'
    as _i3;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/bunner_entity.dart'
    as _i5;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/category_entity.dart'
    as _i12;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/product_entity.dart'
    as _i7;
import 'package:flutter/cupertino.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBannersResponse_0 extends _i1.SmartFake
    implements _i2.BannersResponse {
  _FakeBannersResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_1 extends _i1.SmartFake
    implements _i3.ProductsResponse {
  _FakeProductsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_2 extends _i1.SmartFake
    implements _i4.CategoriesResponse {
  _FakeCategoriesResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBannerEntity_3 extends _i1.SmartFake implements _i5.BannerEntity {
  _FakeBannerEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlignment_4 extends _i1.SmartFake implements _i6.Alignment {
  _FakeAlignment_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductEntity_5 extends _i1.SmartFake implements _i7.ProductEntity {
  _FakeProductEntity_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDatasource extends _i1.Mock
    implements _i8.HomeLocalDatasource {
  MockHomeLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.BannersResponse> getBanners() =>
      (super.noSuchMethod(
            Invocation.method(#getBanners, []),
            returnValue: _i9.Future<_i2.BannersResponse>.value(
              _FakeBannersResponse_0(this, Invocation.method(#getBanners, [])),
            ),
          )
          as _i9.Future<_i2.BannersResponse>);
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i10.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.ProductsResponse> getProducts(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [categoryId]),
            returnValue: _i9.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProducts, [categoryId]),
              ),
            ),
          )
          as _i9.Future<_i3.ProductsResponse>);

  @override
  _i9.Future<_i4.CategoriesResponse> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i9.Future<_i4.CategoriesResponse>.value(
              _FakeCategoriesResponse_2(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i9.Future<_i4.CategoriesResponse>);
}

/// A class which mocks [HomeMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeMapper extends _i1.Mock implements _i11.HomeMapper {
  MockHomeMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.BannerEntity> mapBannersResponseToBannersEntityList(
    List<_i2.BannerResponse>? banners,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mapBannersResponseToBannersEntityList, [
              banners,
            ]),
            returnValue: <_i5.BannerEntity>[],
          )
          as List<_i5.BannerEntity>);

  @override
  _i5.BannerEntity mapBannerResponseToBannerEntity(
    _i2.BannerResponse? banner,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mapBannerResponseToBannerEntity, [banner]),
            returnValue: _FakeBannerEntity_3(
              this,
              Invocation.method(#mapBannerResponseToBannerEntity, [banner]),
            ),
          )
          as _i5.BannerEntity);

  @override
  _i6.Alignment mapAlignment(String? aliment) =>
      (super.noSuchMethod(
            Invocation.method(#mapAlignment, [aliment]),
            returnValue: _FakeAlignment_4(
              this,
              Invocation.method(#mapAlignment, [aliment]),
            ),
          )
          as _i6.Alignment);

  @override
  List<_i7.ProductEntity> mapProductsResponseListToProductEntityList(
    List<_i3.ProductResponse>? products,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mapProductsResponseListToProductEntityList, [
              products,
            ]),
            returnValue: <_i7.ProductEntity>[],
          )
          as List<_i7.ProductEntity>);

  @override
  _i7.ProductEntity mapProductResponseToProductEntity(
    _i3.ProductResponse? product,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mapProductResponseToProductEntity, [product]),
            returnValue: _FakeProductEntity_5(
              this,
              Invocation.method(#mapProductResponseToProductEntity, [product]),
            ),
          )
          as _i7.ProductEntity);

  @override
  List<_i12.CategoryEntity> mapCategoryResponseListToCategoryEntityList(
    List<_i4.CategoryResponse>? categories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mapCategoryResponseListToCategoryEntityList, [
              categories,
            ]),
            returnValue: <_i12.CategoryEntity>[],
          )
          as List<_i12.CategoryEntity>);
}
