// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_bootcamp_c6_clean_arch/test/features/presentaions/view_models/home/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_bootcamp_c6_clean_arch/core/network/app_results.dart'
    as _i4;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/bunner_entity.dart'
    as _i10;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/category_entity.dart'
    as _i8;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/product_entity.dart'
    as _i5;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/use_cases/get_banners_use_case.dart'
    as _i9;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/use_cases/get_categories_use_case.dart'
    as _i7;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/use_cases/get_products_by_id_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetProductsByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsByIdUseCase extends _i1.Mock
    implements _i2.GetProductsByIdUseCase {
  MockGetProductsByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AppResults<List<_i5.ProductEntity>>> call(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [categoryId]),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i5.ProductEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i5.ProductEntity>>>(
                    this,
                    Invocation.method(#call, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i5.ProductEntity>>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i7.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i8.CategoryEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>>);
}

/// A class which mocks [GetBannersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBannersUseCase extends _i1.Mock implements _i9.GetBannersUseCase {
  MockGetBannersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AppResults<List<_i10.BannerEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i10.BannerEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i10.BannerEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i10.BannerEntity>>>);
}
