// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_bootcamp_c6_clean_arch/test/features/domain/use_cases/get_banners_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_bootcamp_c6_clean_arch/core/network/app_results.dart'
    as _i4;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/bunner_entity.dart'
    as _i5;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/category_entity.dart'
    as _i8;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/entities/product_entity.dart'
    as _i7;
import 'package:elevate_bootcamp_c6_clean_arch/features/domain/repo/home_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i2.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AppResults<List<_i5.BannerEntity>>> getBanners() =>
      (super.noSuchMethod(
            Invocation.method(#getBanners, []),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i5.BannerEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i5.BannerEntity>>>(
                    this,
                    Invocation.method(#getBanners, []),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i5.BannerEntity>>>);

  @override
  _i3.Future<_i4.AppResults<List<_i7.ProductEntity>>> getProducts(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [categoryId]),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i7.ProductEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i7.ProductEntity>>>(
                    this,
                    Invocation.method(#getProducts, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i7.ProductEntity>>>);

  @override
  _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>>.value(
                  _i6.dummyValue<_i4.AppResults<List<_i8.CategoryEntity>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResults<List<_i8.CategoryEntity>>>);
}
